server:
  port: 8080
spring:
  security:
    user:
      name: yuanzx
      password: 123456
      roles:
        - admin
        - user
  thymeleaf:
     prefix: classpath:/templates/  # 模板文件存放路径
     suffix: .html                 # 模板文件后缀
     mode: HTML                    # 模板模式 (HTML 是默认值)
     encoding: UTF-8               # 编码格式
     cache: false                  # 是否启用模板缓存，开发阶段建议关闭
     enabled: true
  datasource:
    url: jdbc:mysql://116.198.43.221:3306/book1
    username: root
    password: yuan2005
    driver-class-name: com.mysql.cj.jdbc.Driver